// <auto-generated />
namespace Jobzy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class catogriesadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(catogriesadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202105090321520_catogries-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
